name : Hello World
on: [push] #когда запускаем 
jobs: # список комнад 
    hello-linux: # название job
        runs-on: ubuntu-latest # - oc
        steps: # список того что надо сделать 
          - name: Hello # название шага 
            run: echo "Hello World" #и что делать
          - name: Install the dependecies
            run: pip3 install pyinstaller            
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Run the tests
            run: python3 test.py
          - name: Build the excutable
            run: pyinstaller --windowed --onefile gui.py
          - name: Upload gui-linux
            uses: actions/upload-artifact@v2
            with:
                name: gui-linux
                path: dist/gui
            
    hello-windows: # название job
        runs-on: windows-latest # - oc
        steps: # список того что надо сделать 
          - name: Hello # название шага 
            run: echo "Hello World" #и что делать
          - name: Install the dependecies
            run: pip3 install pyinstaller            
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Run the tests
            run: python3 test.py
          - name: Build the excutable
            run: pyinstaller --windowed --onefile gui.py
          - name: Upload gui-windows
            uses: actions/upload-artifact@v2
            with:
                name: gui-windows
                path: dist/gui.exe    